---
services:
  # wink:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - "5050:5050"
  #   depends_on:
  #     - database
  #   networks:
  #     - app-tier
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db-data/:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
      # environment:
      #   - PGADMIN_DEFAULT_EMAIL=alwindoss84@gmail.com
      #   - PGADMIN_DEFAULT_PASSWORD=password
      # - PGADMIN_DEFAULT_PASSWORD_FILE=pwdfile.txt
    ports:
      - 8081:80
  # valsG_CONTROLLER_LISTENER_NAMES=CONTROLLER
networks:
  app-tier:
    driver: bridge
    